Rework SDK
CodeLighthouse/sdk-python pull request #1
Opened 2020-10-17 00:00 UTC by willtraweek

2020-10-17 17:27 UTC, K-Mistele requested changes

2020-10-17 17:27 UTC, K-Mistele commented on codelighthouse/CodeLighthouse.py
> +        return
Shouldn't there be code here?

2020-10-17 17:27 UTC, K-Mistele commented on codelighthouse/CodeLighthouse.py
> +            self.web_handler.BASE_URL = "https://codelighthouse.io"
Wouldn't this possibly pick up the client's environment variables? For example, if they're in their dev environment and have an environment variable set to "dev", they're gonna send the request to `dev.codelighthouse.io` which isn't what we want.

2020-10-17 17:36 UTC, K-Mistele commented
Couple additional thoughts on this: 
1. we probably don't need them to specify an organization name, right? It'll be tied to their API Key and can be looked up with the API key. If we do need them to specify it, it probably doesn't need to be done with an environment variable.
2. per my comment in the other PR, I'd like to see resource group and resource name being included as well
3. For configuring the module, what I'm envisioning is something like this: they create a config disctionary or whatever and then pass it to the class:

```
options = {
"x_api_key": os.environ.get("CODELIGHTHOUSE_SECRET"),
"environment": os.environ.get("ENVIRONMENT"),
"resource_group": "AWS-lambdas",
"resource_name": "example-lambda"
}
lighthouse = CodeLighthouse(options)
```

2020-10-17 23:11 UTC, willtraweek commented on codelighthouse/CodeLighthouse.py
> +            self.web_handler.BASE_URL = "https://codelighthouse.io"
environment is manually set.  If someone is dumb enough to manually set it to "local" then thats their problem

2020-10-20 22:01 UTC, K-Mistele approved these changes
looks good

2020-10-20 22:01 UTC, merged